spring.application.name=fruit-shop-backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://sql8004.site4now.net:1433;databaseName=db_ac5a7f_data;encrypt=true;trustServerCertificate=true;
spring.datasource.username=db_ac5a7f_data_admin
spring.datasource.password=adkgdnhpce7.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect