spring.application.name=fruit-shop-backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://sql8004.site4now.net:1433;databaseName=db_ac5a7f_data;encrypt=true;trustServerCertificate=true;loginTimeout=60;connectRetryCount=3;connectRetryInterval=10;
spring.datasource.username=db_ac5a7f_data_admin
spring.datasource.password=adkgdnhpce7.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HikariCP connection pool settings (tăng timeout)
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kienhoang0307@gmail.com
spring.mail.password=tgnhsghgkmtwukdw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Email Settings
app.mail.from=Fruit Shop Manager <kienhoang0307@gmail.com>
app.base-url=http://localhost:8080

# File Upload Configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true
